<a href="https://colab.research.google.com/github/u56237z/ml-tf/blob/main/classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

from sklearn.datasets import load_iris

iris = load_iris()

tf.random.set_seed(42)

In [ ]:
iris.data.shape,iris.target.shape

((150, 4), (150,))

In [ ]:
i = tf.random.shuffle([x for x in range(0,iris.data.shape[0])])

X = tf.gather(iris.data,i)
y = tf.gather(iris.target,i)

v = int(iris.data.shape[0]*0.8);
r = int(v*0.8)

X_train = X[:r]
y_train = y[:r]

X_val = X[r:v]
y_val = y[r:v]

X_test = X[v:]
y_test = y[v:]

In [ ]:
model = tf.keras.Sequential([
  tf.keras.layers.Dense(60,activation=tf.keras.activations.relu,input_shape=[4]),
  tf.keras.layers.Dense(3, activation=tf.keras.activations.softmax)
])

model.compile(optimizer=tf.keras.optimizers.SGD(),
              loss=tf.keras.losses.CategoricalCrossentropy()
)

history = model.fit(X_train,tf.one_hot(y_train,3),epochs=2000,verbose=0,validation_data=(X_val,tf.one_hot(y_val,3)))

In [ ]:
model.evaluate(X_test,tf.one_hot(y_test,3))

1/1 [==============================] - 0s 15ms/step - loss: 0.0636


0.06355833262205124

In [ ]:
y_pred = model.predict(X_test)

X_test[4],y_test[4],y_pred[4]

(<tf.Tensor: shape=(4,), dtype=float64, numpy=array([6. , 2.2, 5. , 1.5])>,
 <tf.Tensor: shape=(), dtype=int64, numpy=2>,
 array([3.6236574e-07, 8.8122385e-03, 9.9118739e-01], dtype=float32))